### ISSUE TITLE
Trying to import SVG Grid Image Plugin fails

### ISSUE THREAD

**Issue by berlindave** [oddbird/susy#664]
Hello experts,

I hope this is the appropriate place for my question:
I'm trying to migrate from Susy 2 to 3. When trying to import the SVG Grid Image Plugin by `@import "../../node_modules/susy/sass/plugins/svg-grid";` I get a big bunch of error messages:
```
/MY_PATH/node_modules/css-parse/index.js:62
    throw err;
    ^

Error: missing '}' near line 376:579
    at error (/MY_PATH/node_modules/css-parse/index.js:57:15)
    at declarations (/MY_PATH/node_modules/css-parse/index.js:224:26)
    at rule (/MY_PATH/node_modules/css-parse/index.js:481:21)
    at rules (/MY_PATH/node_modules/css-parse/index.js:103:56)
    at stylesheet (/MY_PATH/node_modules/css-parse/index.js:73:16)
    at module.exports (/MY_PATH/node_modules/css-parse/index.js:485:10)
    at Transform.transform [as _transform] (/MY_PATH/node_modules/gulp-merge-media-queries/index.js:133:19)
    at Transform._read (/MY_PATH/node_modules/gulp-merge-media-queries/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/MY_PATH/node_modules/gulp-merge-media-queries/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/MY_PATH/node_modules/gulp-merge-media-queries/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/MY_PATH/node_modules/gulp-merge-media-queries/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/MY_PATH/node_modules/gulp-merge-media-queries/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at StreamFilter.ondata (/MY_PATH/node_modules/readable-stream/lib/_stream_readable.js:541:20)
    at emitOne (events.js:115:13)
    at StreamFilter.emit (events.js:210:7)
    at readableAddChunk (/MY_PATH/node_modules/readable-stream/lib/_stream_readable.js:212:18)
    at StreamFilter.Readable.push (/MY_PATH/node_modules/readable-stream/lib/_stream_readable.js:171:10)
    at StreamFilter.Transform.push (/MY_PATH/node_modules/readable-stream/lib/_stream_transform.js:123:32)
    at StreamFilterCallback (/MY_PATH/node_modules/streamfilter/src/index.js:30:15)
    at streamfilter.objectMode (/MY_PATH/node_modules/gulp-filter/index.js:19:3)
    at StreamFilter.streamFilterTransform [as _transform] (/MY_PATH/node_modules/streamfilter/src/index.js:28:5)
    at StreamFilter.Transform._read (/MY_PATH/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at StreamFilter.Transform._write (/MY_PATH/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/MY_PATH/node_modules/readable-stream/lib/_stream_writable.js:338:64)
    at writeOrBuffer (/MY_PATH/node_modules/readable-stream/lib/_stream_writable.js:327:5)
    at StreamFilter.Writable.write (/MY_PATH/node_modules/readable-stream/lib/_stream_writable.js:264:11)
    at DestroyableTransform.ondata (internal/streams/legacy.js:16:26)
    at emitOne (events.js:115:13)
    at DestroyableTransform.emit (events.js:210:7)
    at DestroyableTransform.<anonymous> (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
    at emitReadable_ (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/MY_PATH/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at done (/MY_PATH/node_modules/vinyl-fs/lib/dest/writeContents/index.js:11:7)
    at FSReqWrap.oncomplete (fs.js:135:15)
```
What could be the reason?

For your hints many thanks in advance!

**Comment by mirisuzanne** [comment]
Looks like that error comes from a "css-parse" node-module. Do you know what that package is doing? Do you use True+Mocha for testing - I think that might use a CSS parser?

**Comment by berlindave** [comment]
Yes, 'css-parse' seems to be a dependency of 'gulp-merge-media-queries' which I use in my gulpfile.js. When I avoid using 'gulp-merge-media-queries' everything is ok. But this is just I workaround. Unfortunately I'm too much a noob to detect the real conflict between 'css-parse' and the Susy SVG Grid Image Plugin.

**Comment by mirisuzanne** [comment]
If you get the error on import, it seems like CSS-parse is trying to parse your entire Sass path, but gulp-merge-media-queries should probably only deal with your output CSS. I don't know enough about those plugins to know what they were doing. I'd file a bug with one or both of them. Feel free to link back here, so I can follow along.

**Comment by berlindave** [comment]
Thank you, @mirisuzanne , for your hints! I think the problem is that 'gulp-merge-media-queries' has an outdated version of 'css-parse' as a dependency. So I'd rather move away from 'gulp-merge-media-queries'. It seems to have problems with the inline SVG in the stylesheet, which comes from the SVG Grid Image Plugin.
